services:

  # ----------------------------------------------------------------------
  # REVERSE PROXY
  # ----------------------------------------------------------------------
  traefik:
    image: "traefik:v2.11"
    command:
      - --log.level=INFO
      - --api=true
      - --api.dashboard=true
      - --api.insecure=true
      # Entrypoints
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls.certresolver=myresolver
      # letsencrypt
      - --certificatesresolvers.myresolver.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/config/acme.json
      # uncomment to use testing certs
      #- --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=http
      # Docker setup
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.watch=true
    restart: "unless-stopped"
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "traefik:/config"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  # ----------------------------------------------------------------------
  # MESSAGE BROKER
  # ----------------------------------------------------------------------
  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USERNAME:-guest}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASSWORD:-guest}"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  # ----------------------------------------------------------------------
  # CDR HOOK
  # ----------------------------------------------------------------------
  cdrhook:
    image: ncsa/criticalmaas-cdr:${SYSTEM_VERSION}
    hostname: cdrhook
    build: server
    restart: unless-stopped
    depends_on:
      - rabbitmq
    environment:
      CDR_TOKEN: "${CDR_TOKEN}"
      SYSTEM_NAME: ${SYSTEM_NAME}
      SYSTEM_VERSION: ${SYSTEM_VERSION}
      CALLBACK_URL: "https://${SERVER_NAME}${CALLBACK_PATH}"
      CALLBACK_SECRET: "${CALLBACK_SECRET}"
      CALLBACK_USERNAME: "${CALLBACK_USERNAME}"
      CALLBACK_PASSWORD: "${CALLBACK_PASSWORD}"
      RABBITMQ_URI: "amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@rabbitmq/%2F"
      DOWNLOAD_QUEUE: "download"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cdrhook.rule=Host(`${SERVER_NAME}`) && PathPrefix(`${CALLBACK_PATH}`)"

  # ----------------------------------------------------------------------
  # RABBITMQ MONITOR
  # ----------------------------------------------------------------------
  monitor:
    image: ncsa/criticalmaas-monitor:${SYSTEM_VERSION}
    hostname: monitor
    build: monitor
    restart: unless-stopped
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_MGMT_URL: ${RABBITMQ_MGMT_URL}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monitor.rule=Host(`${SERVER_NAME}`) && PathPrefix(`/monitor`)"

  # ----------------------------------------------------------------------
  # DATA PROCESSING PIPELINE
  # use one, or more, per model to be executed
  # ----------------------------------------------------------------------
  pipeline:
    image: ncsa/criticalmaas-pipeline
    build: ../uiuc-pipeline
    runtime: nvidia
    profiles:
      - pipeline
    depends_on:
      - rabbitmq
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command:
      - -v 
      - --data
      - /data
      - --log
      - /logs/logs.latest
      - --output
      - /output
      - --amqp
      - "amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@rabbitmq/%2F"
      - --model
      - golden_muscat
    restart: "unless-stopped"
    volumes:
      - "data:/data"
      - "logs:/logs"
      - "output:/output"

  # ----------------------------------------------------------------------
  # DATA PROCESSING PIPELINE
  # use one, or more, per model to be executed
  # ----------------------------------------------------------------------
  uploader:
    image: ncsa/criticalmaas-uploader
    build: uploader
    restart: "unless-stopped"
    profiles:
      - uploader
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URI: "amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@rabbitmq/%2F"
      CDR_TOKEN: "${CDR_TOKEN}"
    volumes:
      - "output:/output"

volumes:
  traefik:
  rabbitmq:
  data:
  logs:
  output:
