services:
  # Add SSL to traefik
  traefik:
    command:
      - --log.level=INFO
      - --api=true
      - --api.dashboard=true
      - --api.insecure=true
      # Entrypoints
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls.certresolver=myresolver
      # letsencrypt
      - --certificatesresolvers.myresolver.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/config/acme.json
      # uncomment to use testing certs
      #- --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.myresolver.acme.httpchallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=http
      # Docker setup
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.docker.watch=true
    ports:
      - "80:80"
      - "443:443"

  cdrhook:
    environment:
      SYSTEM_NAME: ${SYSTEM_NAME}
      SYSTEM_VERSION: ${SYSTEM_VERSION}
  golden_muscat:
    environment:
      CDR_SYSTEM: ${SYSTEM_NAME}
      CDR_SYSTEM_VERSION: ${SYSTEM_VERSION}

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: /data/volumes/data
      o: bind
  output:
    driver: local
    driver_opts:
      type: none
      device: /data/volumes/output
      o: bind
